/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  // Performance optimization: only generate used utilities
  safelist: [
    // Keep essential animation classes
    'animate-spin',
    'animate-pulse',
    'animate-bounce',
    'animate-fade-in',
    'animate-slide-in',
    'animate-scale-in',
    // Keep focus states
    'focus:ring-2',
    'focus:ring-primary-500',
    'focus-visible:outline-2',
    // Keep accessibility classes
    'sr-only',
    'sr-only-focusable',
  ],
  theme: {
    extend: {
      screens: {
        '3xl': '1920px',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        gray: {
          50: 'var(--gray-50)',
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
        },
        success: {
          DEFAULT: 'var(--success)',
          light: 'var(--success-light)',
          foreground: '#ffffff',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          light: 'var(--warning-light)',
          foreground: '#ffffff',
        },
        error: {
          DEFAULT: 'var(--error)',
          light: 'var(--error-light)',
          foreground: '#ffffff',
        },
        info: {
          DEFAULT: 'var(--info)',
          light: 'var(--info-light)',
          foreground: '#ffffff',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
      },
      fontFamily: {
        sans: ['var(--font-primary)', 'system-ui', 'sans-serif'],
        heading: ['var(--font-heading)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      fontSize: {
        'xs': ['var(--text-xs)', { lineHeight: '1rem' }],
        'sm': ['var(--text-sm)', { lineHeight: '1.25rem' }],
        'base': ['var(--text-base)', { lineHeight: '1.5rem' }],
        'lg': ['var(--text-lg)', { lineHeight: '1.75rem' }],
        'xl': ['var(--text-xl)', { lineHeight: '1.75rem' }],
        '2xl': ['var(--text-2xl)', { lineHeight: '2rem' }],
        '3xl': ['var(--text-3xl)', { lineHeight: '2.25rem' }],
        '4xl': ['var(--text-4xl)', { lineHeight: '2.5rem' }],
        // Professional typography scale
        'display-large': ['3rem', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.05em' }],
        'display-medium': ['var(--text-4xl)', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.05em' }],
        'display-small': ['var(--text-3xl)', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '-0.025em' }],
        'headline-large': ['var(--text-2xl)', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-medium': ['var(--text-xl)', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-small': ['var(--text-lg)', { lineHeight: '1.4', fontWeight: '500' }],
        'body-large': ['var(--text-lg)', { lineHeight: '1.6', fontWeight: '400' }],
        'body-medium': ['var(--text-base)', { lineHeight: '1.6', fontWeight: '400' }],
        'body-small': ['var(--text-sm)', { lineHeight: '1.5', fontWeight: '400' }],
        'label-large': ['var(--text-base)', { lineHeight: '1.4', fontWeight: '500' }],
        'label-medium': ['var(--text-sm)', { lineHeight: '1.4', fontWeight: '500' }],
        'label-small': ['var(--text-xs)', { lineHeight: '1.3', fontWeight: '500', textTransform: 'uppercase', letterSpacing: '0.05em' }],
        'caption': ['var(--text-xs)', { lineHeight: '1.3', fontWeight: '400' }],
        'overline': ['var(--text-xs)', { lineHeight: '1.3', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.1em' }],
      },
      spacing: {
        'xs': 'var(--space-xs)',
        'sm': 'var(--space-sm)',
        'md': 'var(--space-md)',
        'lg': 'var(--space-lg)',
        'xl': 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
        // 8px grid system values
        '0': '0',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '11': '44px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '28': '112px',
        '32': '128px',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        DEFAULT: 'var(--radius)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-out': 'fadeOut 0.5s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
        'slide-out': 'slideOut 0.3s ease-in',
        'scale-in': 'scaleIn 0.2s ease-out',
        'scale-out': 'scaleOut 0.2s ease-in',
        'bounce-subtle': 'bounceSubtle 0.6s ease-in-out',
        'pulse-subtle': 'pulseSubtle 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideIn: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideOut: {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(-10px)', opacity: '0' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
      },
      boxShadow: {
        'soft': 'var(--shadow-soft)',
        'medium': 'var(--shadow-medium)',
        'strong': 'var(--shadow-strong)',
        'glow': 'var(--shadow-glow)',
        'elegant': 'var(--shadow-elegant)',
        'card-hover': 'var(--shadow-card-hover)',
        'button-primary': 'var(--shadow-button-primary)',
        'input-focus': 'var(--shadow-input-focus)',
      },
      backdropBlur: {
        'xs': '2px',
      },
      letterSpacing: {
        'tighter': '-0.05em',
        'tight': '-0.025em',
        'normal': '0',
        'wide': '0.025em',
        'wider': '0.05em',
        'widest': '0.1em',
      },
      lineHeight: {
        'tight': '1.2',
        'snug': '1.3',
        'normal': '1.5',
        'relaxed': '1.6',
        'loose': '1.8',
      },
      fontWeight: {
        'light': '300',
        'normal': '400',
        'medium': '500',
        'semibold': '600',
        'bold': '700',
      },
    },
  },
  plugins: [],
}